// @vitest-environment jsdom
import { beforeEach, describe, expect, it } from "vitest";
import { enhanceSheet, isDnd2024Sheet } from "../src/content/sheet";

describe("sheet enhancement", () => {
  beforeEach(() => { document.body.innerHTML = `<main><div aria-label="D&D 2024 Character Sheet"><span>Strength</span><button>Magic Missile</button></div></main>`; });
  it("détecte explicitement une feuille 2024", () => expect(isDnd2024Sheet()).toBe(true));
  it("détecte la signature DOM réelle sans attribut explicite", () => { document.body.innerHTML = `<section><div>ABILITIES</div><div>AC/SPEED</div><div>FEATURES & TRAITS</div></section>`; expect(isDnd2024Sheet()).toBe(true); });
  it("traduit sans modifier les attributs", () => { enhanceSheet(document, { enabled: true, bilingual: true }); expect(document.querySelector("span")?.textContent).toBe("Force"); expect(document.querySelector("span")?.title).toBe("Strength"); });
  it("ouvre la fiche locale lorsqu’elle existe dans le SRD", () => { enhanceSheet(document, { enabled: true, bilingual: true }); expect(document.querySelector(".dd55-reference [data-dd55-open='spell-projectile-magique']")).not.toBeNull(); expect(document.querySelector(".dd55-reference a")).toBeNull(); });
  it("restaure le libellé quand désactivé", () => { enhanceSheet(document, { enabled: true, bilingual: true }); enhanceSheet(document, { enabled: false, bilingual: true }); expect(document.querySelector("span")?.textContent).toBe("Strength"); });
  it("reste idempotent lors des passages répétés", () => { enhanceSheet(document, { enabled: true, bilingual: true }); enhanceSheet(document, { enabled: true, bilingual: true }); expect(document.querySelectorAll(".dd55-reference")).toHaveLength(1); });
  it("traduit les nœuds imbriqués et les libellés abrégés", () => { document.body.innerHTML = `<div><section><strong><span>ABILITIES</span></strong></section><div>Short</div></div>`; enhanceSheet(document, { enabled: true, bilingual: true }); expect(document.body.textContent).toContain("CARACTÉRISTIQUES"); expect(document.body.textContent).toContain("Court"); });
  it("traduit les actions, états et capacités quelle que soit la casse", () => { document.body.innerHTML = `<div><span>BLINDED</span><span>Dash</span><span>Extra Attack</span><span>Class Features</span></div>`; enhanceSheet(document, { enabled: true, bilingual: true }); expect(document.body.textContent).toContain("Aveuglé"); expect(document.body.textContent).toContain("Foncer"); expect(document.body.textContent).toContain("Attaque supplémentaire"); expect(document.body.textContent).toContain("Capacités de classe"); });
  it("traduit les libellés dynamiques de Roll20", () => { document.body.innerHTML = `<div><span>+8 Attack</span><span>30/120 ft</span><span>Level 4+</span><span>Prerequisite: Fighting Style Feature</span><span>New Item (Attack 2)</span></div>`; enhanceSheet(document, { enabled: true, bilingual: true }); const text = document.body.textContent ?? ""; expect(text).toContain("+8 Attaque"); expect(text).toContain("30/120 pi"); expect(text).toContain("Niveau 4+"); expect(text).toContain("Prérequis : don Style de combat"); expect(text).toContain("Nouvel objet (Attaque 2)"); });
});
